//
// Created by Olcay Taner YILDIZ on 2019-06-03.
//

#ifndef TRANSLATION_SENTENCEALIGNMENTTYPE_H
#define TRANSLATION_SENTENCEALIGNMENTTYPE_H


/**
 * Enumerated class for SentenceAlignmentType
 */
enum class SentenceAlignmentType {
    SUBSTITUTION, DELETION, INSERTION, CONTRACTION, EXPANSION, MERGE
};


#endif //TRANSLATION_SENTENCEALIGNMENTTYPE_H
